### ISSUE TITLE
Error decoding some frames with latest dll

### ISSUE THREAD

**Issue by bnnm** [Thealexbarney/LibAtrac9#3]
Seems the latest version (after the segfault fixes) breaks some files.
Possibly only >2ch files, but not all break though.

Example: [BGMLink_0000.zip](https://github.com/Thealexbarney/LibAtrac9/files/1896035/BGMLink_0000.zip) (from Berserk and the Band of the Hawk PS4, many more there)
Breaks at 0x44c and other frames, works with prev libatrac9.dll
But The Last of Us PS4 >2ch seem to work.

**Comment by Thealexbarney** [comment]
It should be working now. Let me know if it's not.

The issue was caused by incorrect validation values, and an incorrect base gradient curve.
