### ISSUE TITLE
segfault on invalid data 2

### ISSUE THREAD

**Issue by bnnm** [Thealexbarney/LibAtrac9#5]
Another segfault I found while testing bad data. Fails on VGAudio and segfaults LibAtrac9.

I've isolated the offending super-frames, it's the first and second one, ignore the rest of the file. You can also repeat any of those 2 and it'll fail too, but if you only put one doesn't seem to fail (something carried between frames?).
Might be a Franken-frame of half/half from two different frames, since it comes from an FSB that does weird data interleave.

[snd0.zip](https://github.com/Thealexbarney/LibAtrac9/files/2329524/snd0.zip)

**Comment by Thealexbarney** [comment]
Should be fixed in b41861d
